/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DocumentacaoApiIndexRouteImport } from './routes/documentacao-api/index'
import { Route as AppAprovacoesIndexRouteImport } from './routes/app/aprovacoes/index'
import { Route as AppAuditoriaIndexRouteImport } from './routes/app/auditoria/index'
import { Route as AppCentrosDeCustoIndexRouteImport } from './routes/app/centros-de-custo/index'
import { Route as AppCentrosDeCustoNewRouteImport } from './routes/app/centros-de-custo/new'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app/configuracoes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppEmpresasIndexRouteImport } from './routes/app/empresas/index'
import { Route as AppEmpresasNewRouteImport } from './routes/app/empresas/new'
import { Route as AppFornecedoresIndexRouteImport } from './routes/app/fornecedores/index'
import { Route as AppFornecedoresNewRouteImport } from './routes/app/fornecedores/new'
import { Route as AppNotificacoesIndexRouteImport } from './routes/app/notificacoes/index'
import { Route as AppObrasIndexRouteImport } from './routes/app/obras/index'
import { Route as AppObrasWorkIdRouteRouteImport } from './routes/app/obras/$workId/route'
import { Route as AppObrasNewRouteImport } from './routes/app/obras/new'
import { Route as AppOrganizacoesIndexRouteImport } from './routes/app/organizacoes/index'
import { Route as AppOrganizacoesNewRouteImport } from './routes/app/organizacoes/new'
import { Route as AppUsuariosIndexRouteImport } from './routes/app/usuarios/index'
import { Route as AppUsuariosNewRouteImport } from './routes/app/usuarios/new'
import { Route as AuthCadastroIndexRouteImport } from './routes/auth/cadastro/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AppCentrosDeCustoCcIdIndexRouteImport } from './routes/app/centros-de-custo/$ccId/index'
import { Route as AppCentrosDeCustoCcIdEditRouteImport } from './routes/app/centros-de-custo/$ccId/edit'
import { Route as AppEmpresasCompanyIdIndexRouteImport } from './routes/app/empresas/$companyId/index'
import { Route as AppEmpresasCompanyIdEditRouteImport } from './routes/app/empresas/$companyId/edit'
import { Route as AppFornecedoresSupplierIdIndexRouteImport } from './routes/app/fornecedores/$supplierId/index'
import { Route as AppFornecedoresSupplierIdEditRouteImport } from './routes/app/fornecedores/$supplierId/edit'
import { Route as AppObrasWorkIdIndexRouteImport } from './routes/app/obras/$workId/index'
import { Route as AppObrasWorkIdCronogramaRouteImport } from './routes/app/obras/$workId/cronograma'
import { Route as AppObrasCompararIndexRouteImport } from './routes/app/obras/comparar/index'
import { Route as AppOrganizacoesOrgIdIndexRouteImport } from './routes/app/organizacoes/$orgId/index'
import { Route as AppOrganizacoesOrgIdEditRouteImport } from './routes/app/organizacoes/$orgId/edit'
import { Route as AppUsuariosUserIdIndexRouteImport } from './routes/app/usuarios/$userId/index'
import { Route as AppUsuariosUserIdEditRouteImport } from './routes/app/usuarios/$userId/edit'
import { Route as AppCentrosDeCustoCcIdMultiobrasIndexRouteImport } from './routes/app/centros-de-custo/$ccId/multiobras/index'
import { Route as AppCentrosDeCustoCcIdRelatoriosIndexRouteImport } from './routes/app/centros-de-custo/$ccId/relatorios/index'
import { Route as AppObrasWorkIdAprovacoesIndexRouteImport } from './routes/app/obras/$workId/aprovacoes/index'
import { Route as AppObrasWorkIdConfiguracoesIndexRouteImport } from './routes/app/obras/$workId/configuracoes/index'
import { Route as AppObrasWorkIdContratosIndexRouteImport } from './routes/app/obras/$workId/contratos/index'
import { Route as AppObrasWorkIdContratosNewRouteImport } from './routes/app/obras/$workId/contratos/new'
import { Route as AppObrasWorkIdCotacoesIndexRouteImport } from './routes/app/obras/$workId/cotacoes/index'
import { Route as AppObrasWorkIdCotacoesNewRouteImport } from './routes/app/obras/$workId/cotacoes/new'
import { Route as AppObrasWorkIdCustosIndexRouteImport } from './routes/app/obras/$workId/custos/index'
import { Route as AppObrasWorkIdCustosNewRouteImport } from './routes/app/obras/$workId/custos/new'
import { Route as AppObrasWorkIdEstatisticasIndexRouteImport } from './routes/app/obras/$workId/estatisticas/index'
import { Route as AppObrasWorkIdGestaoIndexRouteImport } from './routes/app/obras/$workId/gestao/index'
import { Route as AppObrasWorkIdHistoricoIndexRouteImport } from './routes/app/obras/$workId/historico/index'
import { Route as AppObrasWorkIdImportacoesIndexRouteImport } from './routes/app/obras/$workId/importacoes/index'
import { Route as AppObrasWorkIdMedicoesIndexRouteImport } from './routes/app/obras/$workId/medicoes/index'
import { Route as AppObrasWorkIdMedicoesNewRouteImport } from './routes/app/obras/$workId/medicoes/new'
import { Route as AppObrasWorkIdOrcamentoIndexRouteImport } from './routes/app/obras/$workId/orcamento/index'
import { Route as AppObrasWorkIdOrcamentoEditarRouteImport } from './routes/app/obras/$workId/orcamento/editar'
import { Route as AppOrganizacoesOrgIdMulticentrosIndexRouteImport } from './routes/app/organizacoes/$orgId/multicentros/index'
import { Route as AppOrganizacoesOrgIdRelatoriosIndexRouteImport } from './routes/app/organizacoes/$orgId/relatorios/index'
import { Route as AppObrasWorkIdContratosContractIdIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/index'
import { Route as AppObrasWorkIdContratosContractIdEditRouteImport } from './routes/app/obras/$workId/contratos/$contractId/edit'
import { Route as AppObrasWorkIdCustosCostIdIndexRouteImport } from './routes/app/obras/$workId/custos/$costId/index'
import { Route as AppObrasWorkIdCustosCostIdEditRouteImport } from './routes/app/obras/$workId/custos/$costId/edit'
import { Route as AppObrasWorkIdMedicoesMeasurementIdIndexRouteImport } from './routes/app/obras/$workId/medicoes/$measurementId/index'
import { Route as AppObrasWorkIdMedicoesMeasurementIdEditRouteImport } from './routes/app/obras/$workId/medicoes/$measurementId/edit'
import { Route as AppObrasWorkIdMedicoesMapaIndexRouteImport } from './routes/app/obras/$workId/medicoes/mapa/index'
import { Route as AppObrasWorkIdMedicoesRelatoriosIndexRouteImport } from './routes/app/obras/$workId/medicoes/relatorios/index'
import { Route as AppObrasWorkIdContratosContractIdMedicoesIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/medicoes/index'
import { Route as AppObrasWorkIdContratosContractIdRelatorioIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/relatorio/index'
import { Route as AppObrasWorkIdContratosContractIdServicosIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/servicos/index'
import { Route as AppObrasWorkIdContratosContractIdServicosNewRouteImport } from './routes/app/obras/$workId/contratos/$contractId/servicos/new'
import { Route as AppObrasWorkIdContratosRequestIdAprovacaoIndexRouteImport } from './routes/app/obras/$workId/contratos/$requestId/aprovacao/index'
import { Route as AppObrasWorkIdContratosRequestIdComparativoIndexRouteImport } from './routes/app/obras/$workId/contratos/$requestId/comparativo/index'
import { Route as AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRouteImport } from './routes/app/obras/$workId/medicoes/$measurementId/relatorio/index'
import { Route as AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/index'
import { Route as AppObrasWorkIdContratosContractIdMedicoesMapaIndexRouteImport } from './routes/app/obras/$workId/contratos/$contractId/medicoes/mapa/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocumentacaoApiIndexRoute = DocumentacaoApiIndexRouteImport.update({
  id: '/documentacao-api/',
  path: '/documentacao-api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAprovacoesIndexRoute = AppAprovacoesIndexRouteImport.update({
  id: '/aprovacoes/',
  path: '/aprovacoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditoriaIndexRoute = AppAuditoriaIndexRouteImport.update({
  id: '/auditoria/',
  path: '/auditoria/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCentrosDeCustoIndexRoute = AppCentrosDeCustoIndexRouteImport.update({
  id: '/centros-de-custo/',
  path: '/centros-de-custo/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCentrosDeCustoNewRoute = AppCentrosDeCustoNewRouteImport.update({
  id: '/centros-de-custo/new',
  path: '/centros-de-custo/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmpresasIndexRoute = AppEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmpresasNewRoute = AppEmpresasNewRouteImport.update({
  id: '/empresas/new',
  path: '/empresas/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFornecedoresIndexRoute = AppFornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFornecedoresNewRoute = AppFornecedoresNewRouteImport.update({
  id: '/fornecedores/new',
  path: '/fornecedores/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificacoesIndexRoute = AppNotificacoesIndexRouteImport.update({
  id: '/notificacoes/',
  path: '/notificacoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObrasIndexRoute = AppObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObrasWorkIdRouteRoute = AppObrasWorkIdRouteRouteImport.update({
  id: '/obras/$workId',
  path: '/obras/$workId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObrasNewRoute = AppObrasNewRouteImport.update({
  id: '/obras/new',
  path: '/obras/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizacoesIndexRoute = AppOrganizacoesIndexRouteImport.update({
  id: '/organizacoes/',
  path: '/organizacoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizacoesNewRoute = AppOrganizacoesNewRouteImport.update({
  id: '/organizacoes/new',
  path: '/organizacoes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosNewRoute = AppUsuariosNewRouteImport.update({
  id: '/usuarios/new',
  path: '/usuarios/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCadastroIndexRoute = AuthCadastroIndexRouteImport.update({
  id: '/auth/cadastro/',
  path: '/auth/cadastro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCentrosDeCustoCcIdIndexRoute =
  AppCentrosDeCustoCcIdIndexRouteImport.update({
    id: '/centros-de-custo/$ccId/',
    path: '/centros-de-custo/$ccId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCentrosDeCustoCcIdEditRoute =
  AppCentrosDeCustoCcIdEditRouteImport.update({
    id: '/centros-de-custo/$ccId/edit',
    path: '/centros-de-custo/$ccId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEmpresasCompanyIdIndexRoute =
  AppEmpresasCompanyIdIndexRouteImport.update({
    id: '/empresas/$companyId/',
    path: '/empresas/$companyId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEmpresasCompanyIdEditRoute =
  AppEmpresasCompanyIdEditRouteImport.update({
    id: '/empresas/$companyId/edit',
    path: '/empresas/$companyId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppFornecedoresSupplierIdIndexRoute =
  AppFornecedoresSupplierIdIndexRouteImport.update({
    id: '/fornecedores/$supplierId/',
    path: '/fornecedores/$supplierId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppFornecedoresSupplierIdEditRoute =
  AppFornecedoresSupplierIdEditRouteImport.update({
    id: '/fornecedores/$supplierId/edit',
    path: '/fornecedores/$supplierId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObrasWorkIdIndexRoute = AppObrasWorkIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppObrasWorkIdRouteRoute,
} as any)
const AppObrasWorkIdCronogramaRoute =
  AppObrasWorkIdCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasCompararIndexRoute = AppObrasCompararIndexRouteImport.update({
  id: '/obras/comparar/',
  path: '/obras/comparar/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizacoesOrgIdIndexRoute =
  AppOrganizacoesOrgIdIndexRouteImport.update({
    id: '/organizacoes/$orgId/',
    path: '/organizacoes/$orgId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizacoesOrgIdEditRoute =
  AppOrganizacoesOrgIdEditRouteImport.update({
    id: '/organizacoes/$orgId/edit',
    path: '/organizacoes/$orgId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppUsuariosUserIdIndexRoute = AppUsuariosUserIdIndexRouteImport.update({
  id: '/usuarios/$userId/',
  path: '/usuarios/$userId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosUserIdEditRoute = AppUsuariosUserIdEditRouteImport.update({
  id: '/usuarios/$userId/edit',
  path: '/usuarios/$userId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCentrosDeCustoCcIdMultiobrasIndexRoute =
  AppCentrosDeCustoCcIdMultiobrasIndexRouteImport.update({
    id: '/centros-de-custo/$ccId/multiobras/',
    path: '/centros-de-custo/$ccId/multiobras/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCentrosDeCustoCcIdRelatoriosIndexRoute =
  AppCentrosDeCustoCcIdRelatoriosIndexRouteImport.update({
    id: '/centros-de-custo/$ccId/relatorios/',
    path: '/centros-de-custo/$ccId/relatorios/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObrasWorkIdAprovacoesIndexRoute =
  AppObrasWorkIdAprovacoesIndexRouteImport.update({
    id: '/aprovacoes/',
    path: '/aprovacoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdConfiguracoesIndexRoute =
  AppObrasWorkIdConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosIndexRoute =
  AppObrasWorkIdContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosNewRoute =
  AppObrasWorkIdContratosNewRouteImport.update({
    id: '/contratos/new',
    path: '/contratos/new',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCotacoesIndexRoute =
  AppObrasWorkIdCotacoesIndexRouteImport.update({
    id: '/cotacoes/',
    path: '/cotacoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCotacoesNewRoute =
  AppObrasWorkIdCotacoesNewRouteImport.update({
    id: '/cotacoes/new',
    path: '/cotacoes/new',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCustosIndexRoute =
  AppObrasWorkIdCustosIndexRouteImport.update({
    id: '/custos/',
    path: '/custos/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCustosNewRoute = AppObrasWorkIdCustosNewRouteImport.update({
  id: '/custos/new',
  path: '/custos/new',
  getParentRoute: () => AppObrasWorkIdRouteRoute,
} as any)
const AppObrasWorkIdEstatisticasIndexRoute =
  AppObrasWorkIdEstatisticasIndexRouteImport.update({
    id: '/estatisticas/',
    path: '/estatisticas/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdGestaoIndexRoute =
  AppObrasWorkIdGestaoIndexRouteImport.update({
    id: '/gestao/',
    path: '/gestao/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdHistoricoIndexRoute =
  AppObrasWorkIdHistoricoIndexRouteImport.update({
    id: '/historico/',
    path: '/historico/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdImportacoesIndexRoute =
  AppObrasWorkIdImportacoesIndexRouteImport.update({
    id: '/importacoes/',
    path: '/importacoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesIndexRoute =
  AppObrasWorkIdMedicoesIndexRouteImport.update({
    id: '/medicoes/',
    path: '/medicoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesNewRoute =
  AppObrasWorkIdMedicoesNewRouteImport.update({
    id: '/medicoes/new',
    path: '/medicoes/new',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdOrcamentoIndexRoute =
  AppObrasWorkIdOrcamentoIndexRouteImport.update({
    id: '/orcamento/',
    path: '/orcamento/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdOrcamentoEditarRoute =
  AppObrasWorkIdOrcamentoEditarRouteImport.update({
    id: '/orcamento/editar',
    path: '/orcamento/editar',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppOrganizacoesOrgIdMulticentrosIndexRoute =
  AppOrganizacoesOrgIdMulticentrosIndexRouteImport.update({
    id: '/organizacoes/$orgId/multicentros/',
    path: '/organizacoes/$orgId/multicentros/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizacoesOrgIdRelatoriosIndexRoute =
  AppOrganizacoesOrgIdRelatoriosIndexRouteImport.update({
    id: '/organizacoes/$orgId/relatorios/',
    path: '/organizacoes/$orgId/relatorios/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdIndexRoute =
  AppObrasWorkIdContratosContractIdIndexRouteImport.update({
    id: '/contratos/$contractId/',
    path: '/contratos/$contractId/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdEditRoute =
  AppObrasWorkIdContratosContractIdEditRouteImport.update({
    id: '/contratos/$contractId/edit',
    path: '/contratos/$contractId/edit',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCustosCostIdIndexRoute =
  AppObrasWorkIdCustosCostIdIndexRouteImport.update({
    id: '/custos/$costId/',
    path: '/custos/$costId/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdCustosCostIdEditRoute =
  AppObrasWorkIdCustosCostIdEditRouteImport.update({
    id: '/custos/$costId/edit',
    path: '/custos/$costId/edit',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesMeasurementIdIndexRoute =
  AppObrasWorkIdMedicoesMeasurementIdIndexRouteImport.update({
    id: '/medicoes/$measurementId/',
    path: '/medicoes/$measurementId/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesMeasurementIdEditRoute =
  AppObrasWorkIdMedicoesMeasurementIdEditRouteImport.update({
    id: '/medicoes/$measurementId/edit',
    path: '/medicoes/$measurementId/edit',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesMapaIndexRoute =
  AppObrasWorkIdMedicoesMapaIndexRouteImport.update({
    id: '/medicoes/mapa/',
    path: '/medicoes/mapa/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesRelatoriosIndexRoute =
  AppObrasWorkIdMedicoesRelatoriosIndexRouteImport.update({
    id: '/medicoes/relatorios/',
    path: '/medicoes/relatorios/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdMedicoesIndexRoute =
  AppObrasWorkIdContratosContractIdMedicoesIndexRouteImport.update({
    id: '/contratos/$contractId/medicoes/',
    path: '/contratos/$contractId/medicoes/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdRelatorioIndexRoute =
  AppObrasWorkIdContratosContractIdRelatorioIndexRouteImport.update({
    id: '/contratos/$contractId/relatorio/',
    path: '/contratos/$contractId/relatorio/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdServicosIndexRoute =
  AppObrasWorkIdContratosContractIdServicosIndexRouteImport.update({
    id: '/contratos/$contractId/servicos/',
    path: '/contratos/$contractId/servicos/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdServicosNewRoute =
  AppObrasWorkIdContratosContractIdServicosNewRouteImport.update({
    id: '/contratos/$contractId/servicos/new',
    path: '/contratos/$contractId/servicos/new',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute =
  AppObrasWorkIdContratosRequestIdAprovacaoIndexRouteImport.update({
    id: '/contratos/$requestId/aprovacao/',
    path: '/contratos/$requestId/aprovacao/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosRequestIdComparativoIndexRoute =
  AppObrasWorkIdContratosRequestIdComparativoIndexRouteImport.update({
    id: '/contratos/$requestId/comparativo/',
    path: '/contratos/$requestId/comparativo/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute =
  AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRouteImport.update({
    id: '/medicoes/$measurementId/relatorio/',
    path: '/medicoes/$measurementId/relatorio/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)
const AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute =
  AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRouteImport.update(
    {
      id: '/contratos/$contractId/medicoes/$measurementId/',
      path: '/contratos/$contractId/medicoes/$measurementId/',
      getParentRoute: () => AppObrasWorkIdRouteRoute,
    } as any,
  )
const AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute =
  AppObrasWorkIdContratosContractIdMedicoesMapaIndexRouteImport.update({
    id: '/contratos/$contractId/medicoes/mapa/',
    path: '/contratos/$contractId/medicoes/mapa/',
    getParentRoute: () => AppObrasWorkIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/documentacao-api/': typeof DocumentacaoApiIndexRoute
  '/app/obras/$workId': typeof AppObrasWorkIdRouteRouteWithChildren
  '/app/centros-de-custo/new': typeof AppCentrosDeCustoNewRoute
  '/app/empresas/new': typeof AppEmpresasNewRoute
  '/app/fornecedores/new': typeof AppFornecedoresNewRoute
  '/app/obras/new': typeof AppObrasNewRoute
  '/app/organizacoes/new': typeof AppOrganizacoesNewRoute
  '/app/usuarios/new': typeof AppUsuariosNewRoute
  '/app/aprovacoes/': typeof AppAprovacoesIndexRoute
  '/app/auditoria/': typeof AppAuditoriaIndexRoute
  '/app/centros-de-custo/': typeof AppCentrosDeCustoIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/empresas/': typeof AppEmpresasIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/notificacoes/': typeof AppNotificacoesIndexRoute
  '/app/obras/': typeof AppObrasIndexRoute
  '/app/organizacoes/': typeof AppOrganizacoesIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/auth/cadastro/': typeof AuthCadastroIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/app/centros-de-custo/$ccId/edit': typeof AppCentrosDeCustoCcIdEditRoute
  '/app/empresas/$companyId/edit': typeof AppEmpresasCompanyIdEditRoute
  '/app/fornecedores/$supplierId/edit': typeof AppFornecedoresSupplierIdEditRoute
  '/app/obras/$workId/cronograma': typeof AppObrasWorkIdCronogramaRoute
  '/app/organizacoes/$orgId/edit': typeof AppOrganizacoesOrgIdEditRoute
  '/app/usuarios/$userId/edit': typeof AppUsuariosUserIdEditRoute
  '/app/centros-de-custo/$ccId/': typeof AppCentrosDeCustoCcIdIndexRoute
  '/app/empresas/$companyId/': typeof AppEmpresasCompanyIdIndexRoute
  '/app/fornecedores/$supplierId/': typeof AppFornecedoresSupplierIdIndexRoute
  '/app/obras/$workId/': typeof AppObrasWorkIdIndexRoute
  '/app/obras/comparar/': typeof AppObrasCompararIndexRoute
  '/app/organizacoes/$orgId/': typeof AppOrganizacoesOrgIdIndexRoute
  '/app/usuarios/$userId/': typeof AppUsuariosUserIdIndexRoute
  '/app/obras/$workId/contratos/new': typeof AppObrasWorkIdContratosNewRoute
  '/app/obras/$workId/cotacoes/new': typeof AppObrasWorkIdCotacoesNewRoute
  '/app/obras/$workId/custos/new': typeof AppObrasWorkIdCustosNewRoute
  '/app/obras/$workId/medicoes/new': typeof AppObrasWorkIdMedicoesNewRoute
  '/app/obras/$workId/orcamento/editar': typeof AppObrasWorkIdOrcamentoEditarRoute
  '/app/centros-de-custo/$ccId/multiobras/': typeof AppCentrosDeCustoCcIdMultiobrasIndexRoute
  '/app/centros-de-custo/$ccId/relatorios/': typeof AppCentrosDeCustoCcIdRelatoriosIndexRoute
  '/app/obras/$workId/aprovacoes/': typeof AppObrasWorkIdAprovacoesIndexRoute
  '/app/obras/$workId/configuracoes/': typeof AppObrasWorkIdConfiguracoesIndexRoute
  '/app/obras/$workId/contratos/': typeof AppObrasWorkIdContratosIndexRoute
  '/app/obras/$workId/cotacoes/': typeof AppObrasWorkIdCotacoesIndexRoute
  '/app/obras/$workId/custos/': typeof AppObrasWorkIdCustosIndexRoute
  '/app/obras/$workId/estatisticas/': typeof AppObrasWorkIdEstatisticasIndexRoute
  '/app/obras/$workId/gestao/': typeof AppObrasWorkIdGestaoIndexRoute
  '/app/obras/$workId/historico/': typeof AppObrasWorkIdHistoricoIndexRoute
  '/app/obras/$workId/importacoes/': typeof AppObrasWorkIdImportacoesIndexRoute
  '/app/obras/$workId/medicoes/': typeof AppObrasWorkIdMedicoesIndexRoute
  '/app/obras/$workId/orcamento/': typeof AppObrasWorkIdOrcamentoIndexRoute
  '/app/organizacoes/$orgId/multicentros/': typeof AppOrganizacoesOrgIdMulticentrosIndexRoute
  '/app/organizacoes/$orgId/relatorios/': typeof AppOrganizacoesOrgIdRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/edit': typeof AppObrasWorkIdContratosContractIdEditRoute
  '/app/obras/$workId/custos/$costId/edit': typeof AppObrasWorkIdCustosCostIdEditRoute
  '/app/obras/$workId/medicoes/$measurementId/edit': typeof AppObrasWorkIdMedicoesMeasurementIdEditRoute
  '/app/obras/$workId/contratos/$contractId/': typeof AppObrasWorkIdContratosContractIdIndexRoute
  '/app/obras/$workId/custos/$costId/': typeof AppObrasWorkIdCustosCostIdIndexRoute
  '/app/obras/$workId/medicoes/$measurementId/': typeof AppObrasWorkIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/medicoes/mapa/': typeof AppObrasWorkIdMedicoesMapaIndexRoute
  '/app/obras/$workId/medicoes/relatorios/': typeof AppObrasWorkIdMedicoesRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos/new': typeof AppObrasWorkIdContratosContractIdServicosNewRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/': typeof AppObrasWorkIdContratosContractIdMedicoesIndexRoute
  '/app/obras/$workId/contratos/$contractId/relatorio/': typeof AppObrasWorkIdContratosContractIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos/': typeof AppObrasWorkIdContratosContractIdServicosIndexRoute
  '/app/obras/$workId/contratos/$requestId/aprovacao/': typeof AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute
  '/app/obras/$workId/contratos/$requestId/comparativo/': typeof AppObrasWorkIdContratosRequestIdComparativoIndexRoute
  '/app/obras/$workId/medicoes/$measurementId/relatorio/': typeof AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/': typeof AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/mapa/': typeof AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/documentacao-api': typeof DocumentacaoApiIndexRoute
  '/app/centros-de-custo/new': typeof AppCentrosDeCustoNewRoute
  '/app/empresas/new': typeof AppEmpresasNewRoute
  '/app/fornecedores/new': typeof AppFornecedoresNewRoute
  '/app/obras/new': typeof AppObrasNewRoute
  '/app/organizacoes/new': typeof AppOrganizacoesNewRoute
  '/app/usuarios/new': typeof AppUsuariosNewRoute
  '/app/aprovacoes': typeof AppAprovacoesIndexRoute
  '/app/auditoria': typeof AppAuditoriaIndexRoute
  '/app/centros-de-custo': typeof AppCentrosDeCustoIndexRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/empresas': typeof AppEmpresasIndexRoute
  '/app/fornecedores': typeof AppFornecedoresIndexRoute
  '/app/notificacoes': typeof AppNotificacoesIndexRoute
  '/app/obras': typeof AppObrasIndexRoute
  '/app/organizacoes': typeof AppOrganizacoesIndexRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
  '/auth/cadastro': typeof AuthCadastroIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/app/centros-de-custo/$ccId/edit': typeof AppCentrosDeCustoCcIdEditRoute
  '/app/empresas/$companyId/edit': typeof AppEmpresasCompanyIdEditRoute
  '/app/fornecedores/$supplierId/edit': typeof AppFornecedoresSupplierIdEditRoute
  '/app/obras/$workId/cronograma': typeof AppObrasWorkIdCronogramaRoute
  '/app/organizacoes/$orgId/edit': typeof AppOrganizacoesOrgIdEditRoute
  '/app/usuarios/$userId/edit': typeof AppUsuariosUserIdEditRoute
  '/app/centros-de-custo/$ccId': typeof AppCentrosDeCustoCcIdIndexRoute
  '/app/empresas/$companyId': typeof AppEmpresasCompanyIdIndexRoute
  '/app/fornecedores/$supplierId': typeof AppFornecedoresSupplierIdIndexRoute
  '/app/obras/$workId': typeof AppObrasWorkIdIndexRoute
  '/app/obras/comparar': typeof AppObrasCompararIndexRoute
  '/app/organizacoes/$orgId': typeof AppOrganizacoesOrgIdIndexRoute
  '/app/usuarios/$userId': typeof AppUsuariosUserIdIndexRoute
  '/app/obras/$workId/contratos/new': typeof AppObrasWorkIdContratosNewRoute
  '/app/obras/$workId/cotacoes/new': typeof AppObrasWorkIdCotacoesNewRoute
  '/app/obras/$workId/custos/new': typeof AppObrasWorkIdCustosNewRoute
  '/app/obras/$workId/medicoes/new': typeof AppObrasWorkIdMedicoesNewRoute
  '/app/obras/$workId/orcamento/editar': typeof AppObrasWorkIdOrcamentoEditarRoute
  '/app/centros-de-custo/$ccId/multiobras': typeof AppCentrosDeCustoCcIdMultiobrasIndexRoute
  '/app/centros-de-custo/$ccId/relatorios': typeof AppCentrosDeCustoCcIdRelatoriosIndexRoute
  '/app/obras/$workId/aprovacoes': typeof AppObrasWorkIdAprovacoesIndexRoute
  '/app/obras/$workId/configuracoes': typeof AppObrasWorkIdConfiguracoesIndexRoute
  '/app/obras/$workId/contratos': typeof AppObrasWorkIdContratosIndexRoute
  '/app/obras/$workId/cotacoes': typeof AppObrasWorkIdCotacoesIndexRoute
  '/app/obras/$workId/custos': typeof AppObrasWorkIdCustosIndexRoute
  '/app/obras/$workId/estatisticas': typeof AppObrasWorkIdEstatisticasIndexRoute
  '/app/obras/$workId/gestao': typeof AppObrasWorkIdGestaoIndexRoute
  '/app/obras/$workId/historico': typeof AppObrasWorkIdHistoricoIndexRoute
  '/app/obras/$workId/importacoes': typeof AppObrasWorkIdImportacoesIndexRoute
  '/app/obras/$workId/medicoes': typeof AppObrasWorkIdMedicoesIndexRoute
  '/app/obras/$workId/orcamento': typeof AppObrasWorkIdOrcamentoIndexRoute
  '/app/organizacoes/$orgId/multicentros': typeof AppOrganizacoesOrgIdMulticentrosIndexRoute
  '/app/organizacoes/$orgId/relatorios': typeof AppOrganizacoesOrgIdRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/edit': typeof AppObrasWorkIdContratosContractIdEditRoute
  '/app/obras/$workId/custos/$costId/edit': typeof AppObrasWorkIdCustosCostIdEditRoute
  '/app/obras/$workId/medicoes/$measurementId/edit': typeof AppObrasWorkIdMedicoesMeasurementIdEditRoute
  '/app/obras/$workId/contratos/$contractId': typeof AppObrasWorkIdContratosContractIdIndexRoute
  '/app/obras/$workId/custos/$costId': typeof AppObrasWorkIdCustosCostIdIndexRoute
  '/app/obras/$workId/medicoes/$measurementId': typeof AppObrasWorkIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/medicoes/mapa': typeof AppObrasWorkIdMedicoesMapaIndexRoute
  '/app/obras/$workId/medicoes/relatorios': typeof AppObrasWorkIdMedicoesRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos/new': typeof AppObrasWorkIdContratosContractIdServicosNewRoute
  '/app/obras/$workId/contratos/$contractId/medicoes': typeof AppObrasWorkIdContratosContractIdMedicoesIndexRoute
  '/app/obras/$workId/contratos/$contractId/relatorio': typeof AppObrasWorkIdContratosContractIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos': typeof AppObrasWorkIdContratosContractIdServicosIndexRoute
  '/app/obras/$workId/contratos/$requestId/aprovacao': typeof AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute
  '/app/obras/$workId/contratos/$requestId/comparativo': typeof AppObrasWorkIdContratosRequestIdComparativoIndexRoute
  '/app/obras/$workId/medicoes/$measurementId/relatorio': typeof AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId': typeof AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/mapa': typeof AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/documentacao-api/': typeof DocumentacaoApiIndexRoute
  '/app/obras/$workId': typeof AppObrasWorkIdRouteRouteWithChildren
  '/app/centros-de-custo/new': typeof AppCentrosDeCustoNewRoute
  '/app/empresas/new': typeof AppEmpresasNewRoute
  '/app/fornecedores/new': typeof AppFornecedoresNewRoute
  '/app/obras/new': typeof AppObrasNewRoute
  '/app/organizacoes/new': typeof AppOrganizacoesNewRoute
  '/app/usuarios/new': typeof AppUsuariosNewRoute
  '/app/aprovacoes/': typeof AppAprovacoesIndexRoute
  '/app/auditoria/': typeof AppAuditoriaIndexRoute
  '/app/centros-de-custo/': typeof AppCentrosDeCustoIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/empresas/': typeof AppEmpresasIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/notificacoes/': typeof AppNotificacoesIndexRoute
  '/app/obras/': typeof AppObrasIndexRoute
  '/app/organizacoes/': typeof AppOrganizacoesIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/auth/cadastro/': typeof AuthCadastroIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/app/centros-de-custo/$ccId/edit': typeof AppCentrosDeCustoCcIdEditRoute
  '/app/empresas/$companyId/edit': typeof AppEmpresasCompanyIdEditRoute
  '/app/fornecedores/$supplierId/edit': typeof AppFornecedoresSupplierIdEditRoute
  '/app/obras/$workId/cronograma': typeof AppObrasWorkIdCronogramaRoute
  '/app/organizacoes/$orgId/edit': typeof AppOrganizacoesOrgIdEditRoute
  '/app/usuarios/$userId/edit': typeof AppUsuariosUserIdEditRoute
  '/app/centros-de-custo/$ccId/': typeof AppCentrosDeCustoCcIdIndexRoute
  '/app/empresas/$companyId/': typeof AppEmpresasCompanyIdIndexRoute
  '/app/fornecedores/$supplierId/': typeof AppFornecedoresSupplierIdIndexRoute
  '/app/obras/$workId/': typeof AppObrasWorkIdIndexRoute
  '/app/obras/comparar/': typeof AppObrasCompararIndexRoute
  '/app/organizacoes/$orgId/': typeof AppOrganizacoesOrgIdIndexRoute
  '/app/usuarios/$userId/': typeof AppUsuariosUserIdIndexRoute
  '/app/obras/$workId/contratos/new': typeof AppObrasWorkIdContratosNewRoute
  '/app/obras/$workId/cotacoes/new': typeof AppObrasWorkIdCotacoesNewRoute
  '/app/obras/$workId/custos/new': typeof AppObrasWorkIdCustosNewRoute
  '/app/obras/$workId/medicoes/new': typeof AppObrasWorkIdMedicoesNewRoute
  '/app/obras/$workId/orcamento/editar': typeof AppObrasWorkIdOrcamentoEditarRoute
  '/app/centros-de-custo/$ccId/multiobras/': typeof AppCentrosDeCustoCcIdMultiobrasIndexRoute
  '/app/centros-de-custo/$ccId/relatorios/': typeof AppCentrosDeCustoCcIdRelatoriosIndexRoute
  '/app/obras/$workId/aprovacoes/': typeof AppObrasWorkIdAprovacoesIndexRoute
  '/app/obras/$workId/configuracoes/': typeof AppObrasWorkIdConfiguracoesIndexRoute
  '/app/obras/$workId/contratos/': typeof AppObrasWorkIdContratosIndexRoute
  '/app/obras/$workId/cotacoes/': typeof AppObrasWorkIdCotacoesIndexRoute
  '/app/obras/$workId/custos/': typeof AppObrasWorkIdCustosIndexRoute
  '/app/obras/$workId/estatisticas/': typeof AppObrasWorkIdEstatisticasIndexRoute
  '/app/obras/$workId/gestao/': typeof AppObrasWorkIdGestaoIndexRoute
  '/app/obras/$workId/historico/': typeof AppObrasWorkIdHistoricoIndexRoute
  '/app/obras/$workId/importacoes/': typeof AppObrasWorkIdImportacoesIndexRoute
  '/app/obras/$workId/medicoes/': typeof AppObrasWorkIdMedicoesIndexRoute
  '/app/obras/$workId/orcamento/': typeof AppObrasWorkIdOrcamentoIndexRoute
  '/app/organizacoes/$orgId/multicentros/': typeof AppOrganizacoesOrgIdMulticentrosIndexRoute
  '/app/organizacoes/$orgId/relatorios/': typeof AppOrganizacoesOrgIdRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/edit': typeof AppObrasWorkIdContratosContractIdEditRoute
  '/app/obras/$workId/custos/$costId/edit': typeof AppObrasWorkIdCustosCostIdEditRoute
  '/app/obras/$workId/medicoes/$measurementId/edit': typeof AppObrasWorkIdMedicoesMeasurementIdEditRoute
  '/app/obras/$workId/contratos/$contractId/': typeof AppObrasWorkIdContratosContractIdIndexRoute
  '/app/obras/$workId/custos/$costId/': typeof AppObrasWorkIdCustosCostIdIndexRoute
  '/app/obras/$workId/medicoes/$measurementId/': typeof AppObrasWorkIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/medicoes/mapa/': typeof AppObrasWorkIdMedicoesMapaIndexRoute
  '/app/obras/$workId/medicoes/relatorios/': typeof AppObrasWorkIdMedicoesRelatoriosIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos/new': typeof AppObrasWorkIdContratosContractIdServicosNewRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/': typeof AppObrasWorkIdContratosContractIdMedicoesIndexRoute
  '/app/obras/$workId/contratos/$contractId/relatorio/': typeof AppObrasWorkIdContratosContractIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/servicos/': typeof AppObrasWorkIdContratosContractIdServicosIndexRoute
  '/app/obras/$workId/contratos/$requestId/aprovacao/': typeof AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute
  '/app/obras/$workId/contratos/$requestId/comparativo/': typeof AppObrasWorkIdContratosRequestIdComparativoIndexRoute
  '/app/obras/$workId/medicoes/$measurementId/relatorio/': typeof AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/': typeof AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute
  '/app/obras/$workId/contratos/$contractId/medicoes/mapa/': typeof AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/documentacao-api/'
    | '/app/obras/$workId'
    | '/app/centros-de-custo/new'
    | '/app/empresas/new'
    | '/app/fornecedores/new'
    | '/app/obras/new'
    | '/app/organizacoes/new'
    | '/app/usuarios/new'
    | '/app/aprovacoes/'
    | '/app/auditoria/'
    | '/app/centros-de-custo/'
    | '/app/configuracoes/'
    | '/app/dashboard/'
    | '/app/empresas/'
    | '/app/fornecedores/'
    | '/app/notificacoes/'
    | '/app/obras/'
    | '/app/organizacoes/'
    | '/app/usuarios/'
    | '/auth/cadastro/'
    | '/auth/login/'
    | '/app/centros-de-custo/$ccId/edit'
    | '/app/empresas/$companyId/edit'
    | '/app/fornecedores/$supplierId/edit'
    | '/app/obras/$workId/cronograma'
    | '/app/organizacoes/$orgId/edit'
    | '/app/usuarios/$userId/edit'
    | '/app/centros-de-custo/$ccId/'
    | '/app/empresas/$companyId/'
    | '/app/fornecedores/$supplierId/'
    | '/app/obras/$workId/'
    | '/app/obras/comparar/'
    | '/app/organizacoes/$orgId/'
    | '/app/usuarios/$userId/'
    | '/app/obras/$workId/contratos/new'
    | '/app/obras/$workId/cotacoes/new'
    | '/app/obras/$workId/custos/new'
    | '/app/obras/$workId/medicoes/new'
    | '/app/obras/$workId/orcamento/editar'
    | '/app/centros-de-custo/$ccId/multiobras/'
    | '/app/centros-de-custo/$ccId/relatorios/'
    | '/app/obras/$workId/aprovacoes/'
    | '/app/obras/$workId/configuracoes/'
    | '/app/obras/$workId/contratos/'
    | '/app/obras/$workId/cotacoes/'
    | '/app/obras/$workId/custos/'
    | '/app/obras/$workId/estatisticas/'
    | '/app/obras/$workId/gestao/'
    | '/app/obras/$workId/historico/'
    | '/app/obras/$workId/importacoes/'
    | '/app/obras/$workId/medicoes/'
    | '/app/obras/$workId/orcamento/'
    | '/app/organizacoes/$orgId/multicentros/'
    | '/app/organizacoes/$orgId/relatorios/'
    | '/app/obras/$workId/contratos/$contractId/edit'
    | '/app/obras/$workId/custos/$costId/edit'
    | '/app/obras/$workId/medicoes/$measurementId/edit'
    | '/app/obras/$workId/contratos/$contractId/'
    | '/app/obras/$workId/custos/$costId/'
    | '/app/obras/$workId/medicoes/$measurementId/'
    | '/app/obras/$workId/medicoes/mapa/'
    | '/app/obras/$workId/medicoes/relatorios/'
    | '/app/obras/$workId/contratos/$contractId/servicos/new'
    | '/app/obras/$workId/contratos/$contractId/medicoes/'
    | '/app/obras/$workId/contratos/$contractId/relatorio/'
    | '/app/obras/$workId/contratos/$contractId/servicos/'
    | '/app/obras/$workId/contratos/$requestId/aprovacao/'
    | '/app/obras/$workId/contratos/$requestId/comparativo/'
    | '/app/obras/$workId/medicoes/$measurementId/relatorio/'
    | '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/'
    | '/app/obras/$workId/contratos/$contractId/medicoes/mapa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/documentacao-api'
    | '/app/centros-de-custo/new'
    | '/app/empresas/new'
    | '/app/fornecedores/new'
    | '/app/obras/new'
    | '/app/organizacoes/new'
    | '/app/usuarios/new'
    | '/app/aprovacoes'
    | '/app/auditoria'
    | '/app/centros-de-custo'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/empresas'
    | '/app/fornecedores'
    | '/app/notificacoes'
    | '/app/obras'
    | '/app/organizacoes'
    | '/app/usuarios'
    | '/auth/cadastro'
    | '/auth/login'
    | '/app/centros-de-custo/$ccId/edit'
    | '/app/empresas/$companyId/edit'
    | '/app/fornecedores/$supplierId/edit'
    | '/app/obras/$workId/cronograma'
    | '/app/organizacoes/$orgId/edit'
    | '/app/usuarios/$userId/edit'
    | '/app/centros-de-custo/$ccId'
    | '/app/empresas/$companyId'
    | '/app/fornecedores/$supplierId'
    | '/app/obras/$workId'
    | '/app/obras/comparar'
    | '/app/organizacoes/$orgId'
    | '/app/usuarios/$userId'
    | '/app/obras/$workId/contratos/new'
    | '/app/obras/$workId/cotacoes/new'
    | '/app/obras/$workId/custos/new'
    | '/app/obras/$workId/medicoes/new'
    | '/app/obras/$workId/orcamento/editar'
    | '/app/centros-de-custo/$ccId/multiobras'
    | '/app/centros-de-custo/$ccId/relatorios'
    | '/app/obras/$workId/aprovacoes'
    | '/app/obras/$workId/configuracoes'
    | '/app/obras/$workId/contratos'
    | '/app/obras/$workId/cotacoes'
    | '/app/obras/$workId/custos'
    | '/app/obras/$workId/estatisticas'
    | '/app/obras/$workId/gestao'
    | '/app/obras/$workId/historico'
    | '/app/obras/$workId/importacoes'
    | '/app/obras/$workId/medicoes'
    | '/app/obras/$workId/orcamento'
    | '/app/organizacoes/$orgId/multicentros'
    | '/app/organizacoes/$orgId/relatorios'
    | '/app/obras/$workId/contratos/$contractId/edit'
    | '/app/obras/$workId/custos/$costId/edit'
    | '/app/obras/$workId/medicoes/$measurementId/edit'
    | '/app/obras/$workId/contratos/$contractId'
    | '/app/obras/$workId/custos/$costId'
    | '/app/obras/$workId/medicoes/$measurementId'
    | '/app/obras/$workId/medicoes/mapa'
    | '/app/obras/$workId/medicoes/relatorios'
    | '/app/obras/$workId/contratos/$contractId/servicos/new'
    | '/app/obras/$workId/contratos/$contractId/medicoes'
    | '/app/obras/$workId/contratos/$contractId/relatorio'
    | '/app/obras/$workId/contratos/$contractId/servicos'
    | '/app/obras/$workId/contratos/$requestId/aprovacao'
    | '/app/obras/$workId/contratos/$requestId/comparativo'
    | '/app/obras/$workId/medicoes/$measurementId/relatorio'
    | '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId'
    | '/app/obras/$workId/contratos/$contractId/medicoes/mapa'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/documentacao-api/'
    | '/app/obras/$workId'
    | '/app/centros-de-custo/new'
    | '/app/empresas/new'
    | '/app/fornecedores/new'
    | '/app/obras/new'
    | '/app/organizacoes/new'
    | '/app/usuarios/new'
    | '/app/aprovacoes/'
    | '/app/auditoria/'
    | '/app/centros-de-custo/'
    | '/app/configuracoes/'
    | '/app/dashboard/'
    | '/app/empresas/'
    | '/app/fornecedores/'
    | '/app/notificacoes/'
    | '/app/obras/'
    | '/app/organizacoes/'
    | '/app/usuarios/'
    | '/auth/cadastro/'
    | '/auth/login/'
    | '/app/centros-de-custo/$ccId/edit'
    | '/app/empresas/$companyId/edit'
    | '/app/fornecedores/$supplierId/edit'
    | '/app/obras/$workId/cronograma'
    | '/app/organizacoes/$orgId/edit'
    | '/app/usuarios/$userId/edit'
    | '/app/centros-de-custo/$ccId/'
    | '/app/empresas/$companyId/'
    | '/app/fornecedores/$supplierId/'
    | '/app/obras/$workId/'
    | '/app/obras/comparar/'
    | '/app/organizacoes/$orgId/'
    | '/app/usuarios/$userId/'
    | '/app/obras/$workId/contratos/new'
    | '/app/obras/$workId/cotacoes/new'
    | '/app/obras/$workId/custos/new'
    | '/app/obras/$workId/medicoes/new'
    | '/app/obras/$workId/orcamento/editar'
    | '/app/centros-de-custo/$ccId/multiobras/'
    | '/app/centros-de-custo/$ccId/relatorios/'
    | '/app/obras/$workId/aprovacoes/'
    | '/app/obras/$workId/configuracoes/'
    | '/app/obras/$workId/contratos/'
    | '/app/obras/$workId/cotacoes/'
    | '/app/obras/$workId/custos/'
    | '/app/obras/$workId/estatisticas/'
    | '/app/obras/$workId/gestao/'
    | '/app/obras/$workId/historico/'
    | '/app/obras/$workId/importacoes/'
    | '/app/obras/$workId/medicoes/'
    | '/app/obras/$workId/orcamento/'
    | '/app/organizacoes/$orgId/multicentros/'
    | '/app/organizacoes/$orgId/relatorios/'
    | '/app/obras/$workId/contratos/$contractId/edit'
    | '/app/obras/$workId/custos/$costId/edit'
    | '/app/obras/$workId/medicoes/$measurementId/edit'
    | '/app/obras/$workId/contratos/$contractId/'
    | '/app/obras/$workId/custos/$costId/'
    | '/app/obras/$workId/medicoes/$measurementId/'
    | '/app/obras/$workId/medicoes/mapa/'
    | '/app/obras/$workId/medicoes/relatorios/'
    | '/app/obras/$workId/contratos/$contractId/servicos/new'
    | '/app/obras/$workId/contratos/$contractId/medicoes/'
    | '/app/obras/$workId/contratos/$contractId/relatorio/'
    | '/app/obras/$workId/contratos/$contractId/servicos/'
    | '/app/obras/$workId/contratos/$requestId/aprovacao/'
    | '/app/obras/$workId/contratos/$requestId/comparativo/'
    | '/app/obras/$workId/medicoes/$measurementId/relatorio/'
    | '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/'
    | '/app/obras/$workId/contratos/$contractId/medicoes/mapa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DocumentacaoApiIndexRoute: typeof DocumentacaoApiIndexRoute
  AuthCadastroIndexRoute: typeof AuthCadastroIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/documentacao-api/': {
      id: '/documentacao-api/'
      path: '/documentacao-api'
      fullPath: '/documentacao-api/'
      preLoaderRoute: typeof DocumentacaoApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/aprovacoes/': {
      id: '/app/aprovacoes/'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes/'
      preLoaderRoute: typeof AppAprovacoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/auditoria/': {
      id: '/app/auditoria/'
      path: '/auditoria'
      fullPath: '/app/auditoria/'
      preLoaderRoute: typeof AppAuditoriaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/centros-de-custo/': {
      id: '/app/centros-de-custo/'
      path: '/centros-de-custo'
      fullPath: '/app/centros-de-custo/'
      preLoaderRoute: typeof AppCentrosDeCustoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/centros-de-custo/new': {
      id: '/app/centros-de-custo/new'
      path: '/centros-de-custo/new'
      fullPath: '/app/centros-de-custo/new'
      preLoaderRoute: typeof AppCentrosDeCustoNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/empresas/': {
      id: '/app/empresas/'
      path: '/empresas'
      fullPath: '/app/empresas/'
      preLoaderRoute: typeof AppEmpresasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/empresas/new': {
      id: '/app/empresas/new'
      path: '/empresas/new'
      fullPath: '/app/empresas/new'
      preLoaderRoute: typeof AppEmpresasNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fornecedores/': {
      id: '/app/fornecedores/'
      path: '/fornecedores'
      fullPath: '/app/fornecedores/'
      preLoaderRoute: typeof AppFornecedoresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fornecedores/new': {
      id: '/app/fornecedores/new'
      path: '/fornecedores/new'
      fullPath: '/app/fornecedores/new'
      preLoaderRoute: typeof AppFornecedoresNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notificacoes/': {
      id: '/app/notificacoes/'
      path: '/notificacoes'
      fullPath: '/app/notificacoes/'
      preLoaderRoute: typeof AppNotificacoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/': {
      id: '/app/obras/'
      path: '/obras'
      fullPath: '/app/obras/'
      preLoaderRoute: typeof AppObrasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/$workId': {
      id: '/app/obras/$workId'
      path: '/obras/$workId'
      fullPath: '/app/obras/$workId'
      preLoaderRoute: typeof AppObrasWorkIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/new': {
      id: '/app/obras/new'
      path: '/obras/new'
      fullPath: '/app/obras/new'
      preLoaderRoute: typeof AppObrasNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizacoes/': {
      id: '/app/organizacoes/'
      path: '/organizacoes'
      fullPath: '/app/organizacoes/'
      preLoaderRoute: typeof AppOrganizacoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizacoes/new': {
      id: '/app/organizacoes/new'
      path: '/organizacoes/new'
      fullPath: '/app/organizacoes/new'
      preLoaderRoute: typeof AppOrganizacoesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/': {
      id: '/app/usuarios/'
      path: '/usuarios'
      fullPath: '/app/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/new': {
      id: '/app/usuarios/new'
      path: '/usuarios/new'
      fullPath: '/app/usuarios/new'
      preLoaderRoute: typeof AppUsuariosNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/cadastro/': {
      id: '/auth/cadastro/'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro/'
      preLoaderRoute: typeof AuthCadastroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/centros-de-custo/$ccId/': {
      id: '/app/centros-de-custo/$ccId/'
      path: '/centros-de-custo/$ccId'
      fullPath: '/app/centros-de-custo/$ccId/'
      preLoaderRoute: typeof AppCentrosDeCustoCcIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/centros-de-custo/$ccId/edit': {
      id: '/app/centros-de-custo/$ccId/edit'
      path: '/centros-de-custo/$ccId/edit'
      fullPath: '/app/centros-de-custo/$ccId/edit'
      preLoaderRoute: typeof AppCentrosDeCustoCcIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/empresas/$companyId/': {
      id: '/app/empresas/$companyId/'
      path: '/empresas/$companyId'
      fullPath: '/app/empresas/$companyId/'
      preLoaderRoute: typeof AppEmpresasCompanyIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/empresas/$companyId/edit': {
      id: '/app/empresas/$companyId/edit'
      path: '/empresas/$companyId/edit'
      fullPath: '/app/empresas/$companyId/edit'
      preLoaderRoute: typeof AppEmpresasCompanyIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fornecedores/$supplierId/': {
      id: '/app/fornecedores/$supplierId/'
      path: '/fornecedores/$supplierId'
      fullPath: '/app/fornecedores/$supplierId/'
      preLoaderRoute: typeof AppFornecedoresSupplierIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fornecedores/$supplierId/edit': {
      id: '/app/fornecedores/$supplierId/edit'
      path: '/fornecedores/$supplierId/edit'
      fullPath: '/app/fornecedores/$supplierId/edit'
      preLoaderRoute: typeof AppFornecedoresSupplierIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/$workId/': {
      id: '/app/obras/$workId/'
      path: '/'
      fullPath: '/app/obras/$workId/'
      preLoaderRoute: typeof AppObrasWorkIdIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/cronograma': {
      id: '/app/obras/$workId/cronograma'
      path: '/cronograma'
      fullPath: '/app/obras/$workId/cronograma'
      preLoaderRoute: typeof AppObrasWorkIdCronogramaRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/comparar/': {
      id: '/app/obras/comparar/'
      path: '/obras/comparar'
      fullPath: '/app/obras/comparar/'
      preLoaderRoute: typeof AppObrasCompararIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizacoes/$orgId/': {
      id: '/app/organizacoes/$orgId/'
      path: '/organizacoes/$orgId'
      fullPath: '/app/organizacoes/$orgId/'
      preLoaderRoute: typeof AppOrganizacoesOrgIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizacoes/$orgId/edit': {
      id: '/app/organizacoes/$orgId/edit'
      path: '/organizacoes/$orgId/edit'
      fullPath: '/app/organizacoes/$orgId/edit'
      preLoaderRoute: typeof AppOrganizacoesOrgIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/$userId/': {
      id: '/app/usuarios/$userId/'
      path: '/usuarios/$userId'
      fullPath: '/app/usuarios/$userId/'
      preLoaderRoute: typeof AppUsuariosUserIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usuarios/$userId/edit': {
      id: '/app/usuarios/$userId/edit'
      path: '/usuarios/$userId/edit'
      fullPath: '/app/usuarios/$userId/edit'
      preLoaderRoute: typeof AppUsuariosUserIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/centros-de-custo/$ccId/multiobras/': {
      id: '/app/centros-de-custo/$ccId/multiobras/'
      path: '/centros-de-custo/$ccId/multiobras'
      fullPath: '/app/centros-de-custo/$ccId/multiobras/'
      preLoaderRoute: typeof AppCentrosDeCustoCcIdMultiobrasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/centros-de-custo/$ccId/relatorios/': {
      id: '/app/centros-de-custo/$ccId/relatorios/'
      path: '/centros-de-custo/$ccId/relatorios'
      fullPath: '/app/centros-de-custo/$ccId/relatorios/'
      preLoaderRoute: typeof AppCentrosDeCustoCcIdRelatoriosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/$workId/aprovacoes/': {
      id: '/app/obras/$workId/aprovacoes/'
      path: '/aprovacoes'
      fullPath: '/app/obras/$workId/aprovacoes/'
      preLoaderRoute: typeof AppObrasWorkIdAprovacoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/configuracoes/': {
      id: '/app/obras/$workId/configuracoes/'
      path: '/configuracoes'
      fullPath: '/app/obras/$workId/configuracoes/'
      preLoaderRoute: typeof AppObrasWorkIdConfiguracoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/': {
      id: '/app/obras/$workId/contratos/'
      path: '/contratos'
      fullPath: '/app/obras/$workId/contratos/'
      preLoaderRoute: typeof AppObrasWorkIdContratosIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/new': {
      id: '/app/obras/$workId/contratos/new'
      path: '/contratos/new'
      fullPath: '/app/obras/$workId/contratos/new'
      preLoaderRoute: typeof AppObrasWorkIdContratosNewRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/cotacoes/': {
      id: '/app/obras/$workId/cotacoes/'
      path: '/cotacoes'
      fullPath: '/app/obras/$workId/cotacoes/'
      preLoaderRoute: typeof AppObrasWorkIdCotacoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/cotacoes/new': {
      id: '/app/obras/$workId/cotacoes/new'
      path: '/cotacoes/new'
      fullPath: '/app/obras/$workId/cotacoes/new'
      preLoaderRoute: typeof AppObrasWorkIdCotacoesNewRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/custos/': {
      id: '/app/obras/$workId/custos/'
      path: '/custos'
      fullPath: '/app/obras/$workId/custos/'
      preLoaderRoute: typeof AppObrasWorkIdCustosIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/custos/new': {
      id: '/app/obras/$workId/custos/new'
      path: '/custos/new'
      fullPath: '/app/obras/$workId/custos/new'
      preLoaderRoute: typeof AppObrasWorkIdCustosNewRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/estatisticas/': {
      id: '/app/obras/$workId/estatisticas/'
      path: '/estatisticas'
      fullPath: '/app/obras/$workId/estatisticas/'
      preLoaderRoute: typeof AppObrasWorkIdEstatisticasIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/gestao/': {
      id: '/app/obras/$workId/gestao/'
      path: '/gestao'
      fullPath: '/app/obras/$workId/gestao/'
      preLoaderRoute: typeof AppObrasWorkIdGestaoIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/historico/': {
      id: '/app/obras/$workId/historico/'
      path: '/historico'
      fullPath: '/app/obras/$workId/historico/'
      preLoaderRoute: typeof AppObrasWorkIdHistoricoIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/importacoes/': {
      id: '/app/obras/$workId/importacoes/'
      path: '/importacoes'
      fullPath: '/app/obras/$workId/importacoes/'
      preLoaderRoute: typeof AppObrasWorkIdImportacoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/': {
      id: '/app/obras/$workId/medicoes/'
      path: '/medicoes'
      fullPath: '/app/obras/$workId/medicoes/'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/new': {
      id: '/app/obras/$workId/medicoes/new'
      path: '/medicoes/new'
      fullPath: '/app/obras/$workId/medicoes/new'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesNewRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/orcamento/': {
      id: '/app/obras/$workId/orcamento/'
      path: '/orcamento'
      fullPath: '/app/obras/$workId/orcamento/'
      preLoaderRoute: typeof AppObrasWorkIdOrcamentoIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/orcamento/editar': {
      id: '/app/obras/$workId/orcamento/editar'
      path: '/orcamento/editar'
      fullPath: '/app/obras/$workId/orcamento/editar'
      preLoaderRoute: typeof AppObrasWorkIdOrcamentoEditarRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/organizacoes/$orgId/multicentros/': {
      id: '/app/organizacoes/$orgId/multicentros/'
      path: '/organizacoes/$orgId/multicentros'
      fullPath: '/app/organizacoes/$orgId/multicentros/'
      preLoaderRoute: typeof AppOrganizacoesOrgIdMulticentrosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizacoes/$orgId/relatorios/': {
      id: '/app/organizacoes/$orgId/relatorios/'
      path: '/organizacoes/$orgId/relatorios'
      fullPath: '/app/organizacoes/$orgId/relatorios/'
      preLoaderRoute: typeof AppOrganizacoesOrgIdRelatoriosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/': {
      id: '/app/obras/$workId/contratos/$contractId/'
      path: '/contratos/$contractId'
      fullPath: '/app/obras/$workId/contratos/$contractId/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/edit': {
      id: '/app/obras/$workId/contratos/$contractId/edit'
      path: '/contratos/$contractId/edit'
      fullPath: '/app/obras/$workId/contratos/$contractId/edit'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdEditRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/custos/$costId/': {
      id: '/app/obras/$workId/custos/$costId/'
      path: '/custos/$costId'
      fullPath: '/app/obras/$workId/custos/$costId/'
      preLoaderRoute: typeof AppObrasWorkIdCustosCostIdIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/custos/$costId/edit': {
      id: '/app/obras/$workId/custos/$costId/edit'
      path: '/custos/$costId/edit'
      fullPath: '/app/obras/$workId/custos/$costId/edit'
      preLoaderRoute: typeof AppObrasWorkIdCustosCostIdEditRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/$measurementId/': {
      id: '/app/obras/$workId/medicoes/$measurementId/'
      path: '/medicoes/$measurementId'
      fullPath: '/app/obras/$workId/medicoes/$measurementId/'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesMeasurementIdIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/$measurementId/edit': {
      id: '/app/obras/$workId/medicoes/$measurementId/edit'
      path: '/medicoes/$measurementId/edit'
      fullPath: '/app/obras/$workId/medicoes/$measurementId/edit'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesMeasurementIdEditRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/mapa/': {
      id: '/app/obras/$workId/medicoes/mapa/'
      path: '/medicoes/mapa'
      fullPath: '/app/obras/$workId/medicoes/mapa/'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesMapaIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/relatorios/': {
      id: '/app/obras/$workId/medicoes/relatorios/'
      path: '/medicoes/relatorios'
      fullPath: '/app/obras/$workId/medicoes/relatorios/'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesRelatoriosIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/medicoes/': {
      id: '/app/obras/$workId/contratos/$contractId/medicoes/'
      path: '/contratos/$contractId/medicoes'
      fullPath: '/app/obras/$workId/contratos/$contractId/medicoes/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdMedicoesIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/relatorio/': {
      id: '/app/obras/$workId/contratos/$contractId/relatorio/'
      path: '/contratos/$contractId/relatorio'
      fullPath: '/app/obras/$workId/contratos/$contractId/relatorio/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdRelatorioIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/servicos/': {
      id: '/app/obras/$workId/contratos/$contractId/servicos/'
      path: '/contratos/$contractId/servicos'
      fullPath: '/app/obras/$workId/contratos/$contractId/servicos/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdServicosIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/servicos/new': {
      id: '/app/obras/$workId/contratos/$contractId/servicos/new'
      path: '/contratos/$contractId/servicos/new'
      fullPath: '/app/obras/$workId/contratos/$contractId/servicos/new'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdServicosNewRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$requestId/aprovacao/': {
      id: '/app/obras/$workId/contratos/$requestId/aprovacao/'
      path: '/contratos/$requestId/aprovacao'
      fullPath: '/app/obras/$workId/contratos/$requestId/aprovacao/'
      preLoaderRoute: typeof AppObrasWorkIdContratosRequestIdAprovacaoIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$requestId/comparativo/': {
      id: '/app/obras/$workId/contratos/$requestId/comparativo/'
      path: '/contratos/$requestId/comparativo'
      fullPath: '/app/obras/$workId/contratos/$requestId/comparativo/'
      preLoaderRoute: typeof AppObrasWorkIdContratosRequestIdComparativoIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/medicoes/$measurementId/relatorio/': {
      id: '/app/obras/$workId/medicoes/$measurementId/relatorio/'
      path: '/medicoes/$measurementId/relatorio'
      fullPath: '/app/obras/$workId/medicoes/$measurementId/relatorio/'
      preLoaderRoute: typeof AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/': {
      id: '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/'
      path: '/contratos/$contractId/medicoes/$measurementId'
      fullPath: '/app/obras/$workId/contratos/$contractId/medicoes/$measurementId/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
    '/app/obras/$workId/contratos/$contractId/medicoes/mapa/': {
      id: '/app/obras/$workId/contratos/$contractId/medicoes/mapa/'
      path: '/contratos/$contractId/medicoes/mapa'
      fullPath: '/app/obras/$workId/contratos/$contractId/medicoes/mapa/'
      preLoaderRoute: typeof AppObrasWorkIdContratosContractIdMedicoesMapaIndexRouteImport
      parentRoute: typeof AppObrasWorkIdRouteRoute
    }
  }
}

interface AppObrasWorkIdRouteRouteChildren {
  AppObrasWorkIdCronogramaRoute: typeof AppObrasWorkIdCronogramaRoute
  AppObrasWorkIdIndexRoute: typeof AppObrasWorkIdIndexRoute
  AppObrasWorkIdContratosNewRoute: typeof AppObrasWorkIdContratosNewRoute
  AppObrasWorkIdCotacoesNewRoute: typeof AppObrasWorkIdCotacoesNewRoute
  AppObrasWorkIdCustosNewRoute: typeof AppObrasWorkIdCustosNewRoute
  AppObrasWorkIdMedicoesNewRoute: typeof AppObrasWorkIdMedicoesNewRoute
  AppObrasWorkIdOrcamentoEditarRoute: typeof AppObrasWorkIdOrcamentoEditarRoute
  AppObrasWorkIdAprovacoesIndexRoute: typeof AppObrasWorkIdAprovacoesIndexRoute
  AppObrasWorkIdConfiguracoesIndexRoute: typeof AppObrasWorkIdConfiguracoesIndexRoute
  AppObrasWorkIdContratosIndexRoute: typeof AppObrasWorkIdContratosIndexRoute
  AppObrasWorkIdCotacoesIndexRoute: typeof AppObrasWorkIdCotacoesIndexRoute
  AppObrasWorkIdCustosIndexRoute: typeof AppObrasWorkIdCustosIndexRoute
  AppObrasWorkIdEstatisticasIndexRoute: typeof AppObrasWorkIdEstatisticasIndexRoute
  AppObrasWorkIdGestaoIndexRoute: typeof AppObrasWorkIdGestaoIndexRoute
  AppObrasWorkIdHistoricoIndexRoute: typeof AppObrasWorkIdHistoricoIndexRoute
  AppObrasWorkIdImportacoesIndexRoute: typeof AppObrasWorkIdImportacoesIndexRoute
  AppObrasWorkIdMedicoesIndexRoute: typeof AppObrasWorkIdMedicoesIndexRoute
  AppObrasWorkIdOrcamentoIndexRoute: typeof AppObrasWorkIdOrcamentoIndexRoute
  AppObrasWorkIdContratosContractIdEditRoute: typeof AppObrasWorkIdContratosContractIdEditRoute
  AppObrasWorkIdCustosCostIdEditRoute: typeof AppObrasWorkIdCustosCostIdEditRoute
  AppObrasWorkIdMedicoesMeasurementIdEditRoute: typeof AppObrasWorkIdMedicoesMeasurementIdEditRoute
  AppObrasWorkIdContratosContractIdIndexRoute: typeof AppObrasWorkIdContratosContractIdIndexRoute
  AppObrasWorkIdCustosCostIdIndexRoute: typeof AppObrasWorkIdCustosCostIdIndexRoute
  AppObrasWorkIdMedicoesMeasurementIdIndexRoute: typeof AppObrasWorkIdMedicoesMeasurementIdIndexRoute
  AppObrasWorkIdMedicoesMapaIndexRoute: typeof AppObrasWorkIdMedicoesMapaIndexRoute
  AppObrasWorkIdMedicoesRelatoriosIndexRoute: typeof AppObrasWorkIdMedicoesRelatoriosIndexRoute
  AppObrasWorkIdContratosContractIdServicosNewRoute: typeof AppObrasWorkIdContratosContractIdServicosNewRoute
  AppObrasWorkIdContratosContractIdMedicoesIndexRoute: typeof AppObrasWorkIdContratosContractIdMedicoesIndexRoute
  AppObrasWorkIdContratosContractIdRelatorioIndexRoute: typeof AppObrasWorkIdContratosContractIdRelatorioIndexRoute
  AppObrasWorkIdContratosContractIdServicosIndexRoute: typeof AppObrasWorkIdContratosContractIdServicosIndexRoute
  AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute: typeof AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute
  AppObrasWorkIdContratosRequestIdComparativoIndexRoute: typeof AppObrasWorkIdContratosRequestIdComparativoIndexRoute
  AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute: typeof AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute
  AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute: typeof AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute
  AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute: typeof AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute
}

const AppObrasWorkIdRouteRouteChildren: AppObrasWorkIdRouteRouteChildren = {
  AppObrasWorkIdCronogramaRoute: AppObrasWorkIdCronogramaRoute,
  AppObrasWorkIdIndexRoute: AppObrasWorkIdIndexRoute,
  AppObrasWorkIdContratosNewRoute: AppObrasWorkIdContratosNewRoute,
  AppObrasWorkIdCotacoesNewRoute: AppObrasWorkIdCotacoesNewRoute,
  AppObrasWorkIdCustosNewRoute: AppObrasWorkIdCustosNewRoute,
  AppObrasWorkIdMedicoesNewRoute: AppObrasWorkIdMedicoesNewRoute,
  AppObrasWorkIdOrcamentoEditarRoute: AppObrasWorkIdOrcamentoEditarRoute,
  AppObrasWorkIdAprovacoesIndexRoute: AppObrasWorkIdAprovacoesIndexRoute,
  AppObrasWorkIdConfiguracoesIndexRoute: AppObrasWorkIdConfiguracoesIndexRoute,
  AppObrasWorkIdContratosIndexRoute: AppObrasWorkIdContratosIndexRoute,
  AppObrasWorkIdCotacoesIndexRoute: AppObrasWorkIdCotacoesIndexRoute,
  AppObrasWorkIdCustosIndexRoute: AppObrasWorkIdCustosIndexRoute,
  AppObrasWorkIdEstatisticasIndexRoute: AppObrasWorkIdEstatisticasIndexRoute,
  AppObrasWorkIdGestaoIndexRoute: AppObrasWorkIdGestaoIndexRoute,
  AppObrasWorkIdHistoricoIndexRoute: AppObrasWorkIdHistoricoIndexRoute,
  AppObrasWorkIdImportacoesIndexRoute: AppObrasWorkIdImportacoesIndexRoute,
  AppObrasWorkIdMedicoesIndexRoute: AppObrasWorkIdMedicoesIndexRoute,
  AppObrasWorkIdOrcamentoIndexRoute: AppObrasWorkIdOrcamentoIndexRoute,
  AppObrasWorkIdContratosContractIdEditRoute:
    AppObrasWorkIdContratosContractIdEditRoute,
  AppObrasWorkIdCustosCostIdEditRoute: AppObrasWorkIdCustosCostIdEditRoute,
  AppObrasWorkIdMedicoesMeasurementIdEditRoute:
    AppObrasWorkIdMedicoesMeasurementIdEditRoute,
  AppObrasWorkIdContratosContractIdIndexRoute:
    AppObrasWorkIdContratosContractIdIndexRoute,
  AppObrasWorkIdCustosCostIdIndexRoute: AppObrasWorkIdCustosCostIdIndexRoute,
  AppObrasWorkIdMedicoesMeasurementIdIndexRoute:
    AppObrasWorkIdMedicoesMeasurementIdIndexRoute,
  AppObrasWorkIdMedicoesMapaIndexRoute: AppObrasWorkIdMedicoesMapaIndexRoute,
  AppObrasWorkIdMedicoesRelatoriosIndexRoute:
    AppObrasWorkIdMedicoesRelatoriosIndexRoute,
  AppObrasWorkIdContratosContractIdServicosNewRoute:
    AppObrasWorkIdContratosContractIdServicosNewRoute,
  AppObrasWorkIdContratosContractIdMedicoesIndexRoute:
    AppObrasWorkIdContratosContractIdMedicoesIndexRoute,
  AppObrasWorkIdContratosContractIdRelatorioIndexRoute:
    AppObrasWorkIdContratosContractIdRelatorioIndexRoute,
  AppObrasWorkIdContratosContractIdServicosIndexRoute:
    AppObrasWorkIdContratosContractIdServicosIndexRoute,
  AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute:
    AppObrasWorkIdContratosRequestIdAprovacaoIndexRoute,
  AppObrasWorkIdContratosRequestIdComparativoIndexRoute:
    AppObrasWorkIdContratosRequestIdComparativoIndexRoute,
  AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute:
    AppObrasWorkIdMedicoesMeasurementIdRelatorioIndexRoute,
  AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute:
    AppObrasWorkIdContratosContractIdMedicoesMeasurementIdIndexRoute,
  AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute:
    AppObrasWorkIdContratosContractIdMedicoesMapaIndexRoute,
}

const AppObrasWorkIdRouteRouteWithChildren =
  AppObrasWorkIdRouteRoute._addFileChildren(AppObrasWorkIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppObrasWorkIdRouteRoute: typeof AppObrasWorkIdRouteRouteWithChildren
  AppCentrosDeCustoNewRoute: typeof AppCentrosDeCustoNewRoute
  AppEmpresasNewRoute: typeof AppEmpresasNewRoute
  AppFornecedoresNewRoute: typeof AppFornecedoresNewRoute
  AppObrasNewRoute: typeof AppObrasNewRoute
  AppOrganizacoesNewRoute: typeof AppOrganizacoesNewRoute
  AppUsuariosNewRoute: typeof AppUsuariosNewRoute
  AppAprovacoesIndexRoute: typeof AppAprovacoesIndexRoute
  AppAuditoriaIndexRoute: typeof AppAuditoriaIndexRoute
  AppCentrosDeCustoIndexRoute: typeof AppCentrosDeCustoIndexRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEmpresasIndexRoute: typeof AppEmpresasIndexRoute
  AppFornecedoresIndexRoute: typeof AppFornecedoresIndexRoute
  AppNotificacoesIndexRoute: typeof AppNotificacoesIndexRoute
  AppObrasIndexRoute: typeof AppObrasIndexRoute
  AppOrganizacoesIndexRoute: typeof AppOrganizacoesIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
  AppCentrosDeCustoCcIdEditRoute: typeof AppCentrosDeCustoCcIdEditRoute
  AppEmpresasCompanyIdEditRoute: typeof AppEmpresasCompanyIdEditRoute
  AppFornecedoresSupplierIdEditRoute: typeof AppFornecedoresSupplierIdEditRoute
  AppOrganizacoesOrgIdEditRoute: typeof AppOrganizacoesOrgIdEditRoute
  AppUsuariosUserIdEditRoute: typeof AppUsuariosUserIdEditRoute
  AppCentrosDeCustoCcIdIndexRoute: typeof AppCentrosDeCustoCcIdIndexRoute
  AppEmpresasCompanyIdIndexRoute: typeof AppEmpresasCompanyIdIndexRoute
  AppFornecedoresSupplierIdIndexRoute: typeof AppFornecedoresSupplierIdIndexRoute
  AppObrasCompararIndexRoute: typeof AppObrasCompararIndexRoute
  AppOrganizacoesOrgIdIndexRoute: typeof AppOrganizacoesOrgIdIndexRoute
  AppUsuariosUserIdIndexRoute: typeof AppUsuariosUserIdIndexRoute
  AppCentrosDeCustoCcIdMultiobrasIndexRoute: typeof AppCentrosDeCustoCcIdMultiobrasIndexRoute
  AppCentrosDeCustoCcIdRelatoriosIndexRoute: typeof AppCentrosDeCustoCcIdRelatoriosIndexRoute
  AppOrganizacoesOrgIdMulticentrosIndexRoute: typeof AppOrganizacoesOrgIdMulticentrosIndexRoute
  AppOrganizacoesOrgIdRelatoriosIndexRoute: typeof AppOrganizacoesOrgIdRelatoriosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppObrasWorkIdRouteRoute: AppObrasWorkIdRouteRouteWithChildren,
  AppCentrosDeCustoNewRoute: AppCentrosDeCustoNewRoute,
  AppEmpresasNewRoute: AppEmpresasNewRoute,
  AppFornecedoresNewRoute: AppFornecedoresNewRoute,
  AppObrasNewRoute: AppObrasNewRoute,
  AppOrganizacoesNewRoute: AppOrganizacoesNewRoute,
  AppUsuariosNewRoute: AppUsuariosNewRoute,
  AppAprovacoesIndexRoute: AppAprovacoesIndexRoute,
  AppAuditoriaIndexRoute: AppAuditoriaIndexRoute,
  AppCentrosDeCustoIndexRoute: AppCentrosDeCustoIndexRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEmpresasIndexRoute: AppEmpresasIndexRoute,
  AppFornecedoresIndexRoute: AppFornecedoresIndexRoute,
  AppNotificacoesIndexRoute: AppNotificacoesIndexRoute,
  AppObrasIndexRoute: AppObrasIndexRoute,
  AppOrganizacoesIndexRoute: AppOrganizacoesIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
  AppCentrosDeCustoCcIdEditRoute: AppCentrosDeCustoCcIdEditRoute,
  AppEmpresasCompanyIdEditRoute: AppEmpresasCompanyIdEditRoute,
  AppFornecedoresSupplierIdEditRoute: AppFornecedoresSupplierIdEditRoute,
  AppOrganizacoesOrgIdEditRoute: AppOrganizacoesOrgIdEditRoute,
  AppUsuariosUserIdEditRoute: AppUsuariosUserIdEditRoute,
  AppCentrosDeCustoCcIdIndexRoute: AppCentrosDeCustoCcIdIndexRoute,
  AppEmpresasCompanyIdIndexRoute: AppEmpresasCompanyIdIndexRoute,
  AppFornecedoresSupplierIdIndexRoute: AppFornecedoresSupplierIdIndexRoute,
  AppObrasCompararIndexRoute: AppObrasCompararIndexRoute,
  AppOrganizacoesOrgIdIndexRoute: AppOrganizacoesOrgIdIndexRoute,
  AppUsuariosUserIdIndexRoute: AppUsuariosUserIdIndexRoute,
  AppCentrosDeCustoCcIdMultiobrasIndexRoute:
    AppCentrosDeCustoCcIdMultiobrasIndexRoute,
  AppCentrosDeCustoCcIdRelatoriosIndexRoute:
    AppCentrosDeCustoCcIdRelatoriosIndexRoute,
  AppOrganizacoesOrgIdMulticentrosIndexRoute:
    AppOrganizacoesOrgIdMulticentrosIndexRoute,
  AppOrganizacoesOrgIdRelatoriosIndexRoute:
    AppOrganizacoesOrgIdRelatoriosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DocumentacaoApiIndexRoute: DocumentacaoApiIndexRoute,
  AuthCadastroIndexRoute: AuthCadastroIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
